components:
  schemas:
    mainComponent:
      properties:
        about:
          example: https://www.metromadrid.es//es/viaja_en_metro/red_de_metro/estaciones/Plaza_Castilla.html
          type: string
        hasEscalator:
          example: 'true'
          type: string
        hasLift:
          example: 'true'
          type: string
        hasTravelator:
          example: 'false'
          type: string
        lineAbout:
          example: https://www.metromadrid.es//es/viaja_en_metro/red_de_metro/lineas_y_horarios/linea09.html
          type: string
        lineID:
          example: N15c3932d937e4e1b8cb30623cd1d55a9
          type: string
        lineName:
          example: Linea 9
          type: string
        routeService:
          example: https://www.metromadrid.es/es/index.html
          type: string
        stationName:
          example: Plaza de Castilla
          type: string
        transfer:
          example: Autobuses Interurbanos
          type: string
      type: object
      xml:
        name: mainComponent
info:
  description: Obtaining the demodata
  title: demodata
  version: 1.0.0
openapi: 3.0.1
paths:
  /:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: getdemodata
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: stationName
        in: query
        name: stationName
        schema:
          type: string
      - description: about
        in: query
        name: about
        schema:
          type: string
      - description: hasEscalator
        in: query
        name: hasEscalator
        schema:
          type: string
      - description: hasLift
        in: query
        name: hasLift
        schema:
          type: string
      - description: hasTravelator
        in: query
        name: hasTravelator
        schema:
          type: string
      - description: transfer
        in: query
        name: transfer
        schema:
          type: string
      - description: lineAbout
        in: query
        name: lineAbout
        schema:
          type: string
      - description: lineID
        in: query
        name: lineID
        schema:
          type: string
      - description: lineName
        in: query
        name: lineName
        schema:
          type: string
      - description: routeService
        in: query
        name: routeService
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET demodata
  /about/{about}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: getabout
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: about
        in: path
        name: about
        required: true
        schema:
          default: https://www.metromadrid.es//es/viaja_en_metro/red_de_metro/estaciones/Plaza_Castilla.html
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET about
  /hasEscalator/{hasEscalator}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: gethasEscalator
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: hasEscalator
        in: path
        name: hasEscalator
        required: true
        schema:
          default: 'true'
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET hasEscalator
  /hasLift/{hasLift}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: gethasLift
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: hasLift
        in: path
        name: hasLift
        required: true
        schema:
          default: 'true'
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET hasLift
  /hasTravelator/{hasTravelator}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: gethasTravelator
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: hasTravelator
        in: path
        name: hasTravelator
        required: true
        schema:
          default: 'false'
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET hasTravelator
  /lineAbout/{lineAbout}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: getlineAbout
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: lineAbout
        in: path
        name: lineAbout
        required: true
        schema:
          default: https://www.metromadrid.es//es/viaja_en_metro/red_de_metro/lineas_y_horarios/linea09.html
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET lineAbout
  /lineID/{lineID}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: getlineID
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: lineID
        in: path
        name: lineID
        required: true
        schema:
          default: N15c3932d937e4e1b8cb30623cd1d55a9
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET lineID
  /lineName/{lineName}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: getlineName
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: lineName
        in: path
        name: lineName
        required: true
        schema:
          default: Linea 9
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET lineName
  /routeService/{routeService}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: getrouteService
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: routeService
        in: path
        name: routeService
        required: true
        schema:
          default: https://www.metromadrid.es/es/index.html
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET routeService
  /stationName/{stationName}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: getstationName
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: stationName
        in: path
        name: stationName
        required: true
        schema:
          default: Plaza de Castilla
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET stationName
  /transfer/{transfer}:
    get:
      description: Use value 'all' in a parameter for non-empty values
      operationId: gettransfer
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      - description: Visualisation of the data via charts
        in: query
        name: visualisation
        schema:
          type: string
      - description: transfer
        in: path
        name: transfer
        required: true
        schema:
          default: Autobuses Interurbanos
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET transfer
  /visualisation:
    get:
      description: Get visualisation charts of the data
      operationId: getvisualisation
      parameters:
      - description: Maximum number of results
        in: query
        name: limit
        schema:
          default: 10000
          type: integer
      - description: Starting index for results
        in: query
        name: offset
        schema:
          default: 0
          type: integer
      responses:
        '200':
          content:
            text/html:
              schema:
                type: string
          description: successful operation
      summary: GET visualisation charts
servers:
- url: http://localhost:8080/
